function check_infant_look_to_highlighted_obj(subjects)

eeglab;

fid=fopen('/home/jbonaiuto/Dropbox/joint_attention/infant_gaze_eeg/erd/erd_results/obs/looks_to_highlighted_obj.csv','w');
fprintf(fid,'Subject,Age,Condition,Prop\n');

for idx=1:length(subjects)
    subj_info=subjects(idx);
    for age_idx=1:length(subj_info.ages)
        age=subj_info.ages{age_idx};
        data_dir=fullfile('/data/infant_gaze_eeg', age,'preprocessed', num2str(subj_info.subj_id));
        
        static=pop_loadset('filepath',data_dir,'filename',sprintf('%d.static.epochs.set',subj_info.subj_id));        
        unshuffled_static = pop_selectevent(static, 'type', {'ima1'},...
            'shuf', 0, 'deleteevents', 'off', 'deleteepochs', 'on',...
            'invertepochs', 'off');
        unshuffled_congruent_static = pop_selectevent(unshuffled_static, 'type',...
            {'ima1'}, 'gaze', {'cong'}, 'deleteevents', 'off',...
            'deleteepochs', 'on', 'invertepochs', 'off');
        unshuffled_incongruent_static = pop_selectevent(unshuffled_static, 'type',...
            {'ima1'}, 'gaze', {'inco'}, 'deleteevents', 'off',...
            'deleteepochs', 'on', 'invertepochs', 'off');
        shuffled_static = pop_selectevent(static, 'type', {'ima1'}, ...
            'shuf', 1, 'deleteevents', 'off', 'deleteepochs', 'on',...
            'invertepochs', 'off');
                    
        mov1=pop_loadset('filepath',data_dir,'filename',sprintf('%d.mov1.epochs.set',subj_info.subj_id));
        unshuffled_mov1 = pop_selectevent(mov1, 'type', {'mov1'},...
            'shuf', 0, 'deleteevents', 'off', 'deleteepochs', 'on',...
            'invertepochs', 'off');
        unshuffled_congruent_mov1 = pop_selectevent(unshuffled_mov1, 'type',...
            {'mov1'}, 'gaze', {'cong'}, 'deleteevents', 'off',...
            'deleteepochs', 'on', 'invertepochs', 'off');
        unshuffled_incongruent_mov1 = pop_selectevent(unshuffled_mov1, 'type',...
            {'mov1'}, 'gaze', {'inco'}, 'deleteevents', 'off',...
            'deleteepochs', 'on', 'invertepochs', 'off');
        shuffled_mov1 = pop_selectevent(mov1, 'type', {'mov1'}, ...
            'shuf', 1, 'deleteevents', 'off', 'deleteepochs', 'on',...
            'invertepochs', 'off');
        
        fprintf(fid,'%d,%s,congruent,%.4f\n', subj_info.subj_id, age, unshuffled_congruent_mov1.trials/unshuffled_congruent_static.trials);
        fprintf(fid,'%d,%s,incongruent,%.4f\n', subj_info.subj_id, age, unshuffled_incongruent_mov1.trials/unshuffled_incongruent_static.trials);
        fprintf(fid,'%d,%s,scrambled,%.4f\n', subj_info.subj_id, age, shuffled_mov1.trials/shuffled_static.trials);
    end
end

fclose(fid);