function precompute_ersps(subj_info, age, varargin)

defaults=struct();
params=struct(varargin{:});
for f = fieldnames(defaults)',
    if ~isfield(params, f{1}),
        params.(f{1}) = defaults.(f{1});
    end
end

preprocess_dir=fullfile('/data/infant_gaze_eeg/',age,'preprocessed',...
    num2str(subj_info.subj_id));

fname=fullfile(preprocess_dir, sprintf('%d.head_turns.epoch_reject.set', ...
    subj_info.subj_id));
if exist(fname,'file')==2
    % Load data file
    data=pop_loadset(fname);
    % Compute trial TF (not baseline-corrected)
    std_ersp(data, 'type', 'ersp',...
        'trialindices', [1:data.trials], 'cycles', 0,...
        'nfreqs', 100, 'ntimesout', 400,...
        'freqs', [2 35], 'freqscale', 'linear',...
        'baseline', NaN, 'winsize',128,...
        'padratio', 16, 'channels', {data.chanlocs.labels}',...
        'verbose', 'on', 'savefile', 'on', 'recompute', 'on',...
        'savetrials','on');
end
