function reject_trials(subj_id, age, condition, trials, trial_type)

preprocess_dir=fullfile('/data/infant_gaze_eeg/',age,'preprocessed',num2str(subj_id));
fname=fullfile(preprocess_dir,sprintf('%d.whole.%s.%s.set',subj_id,condition,trial_type));

data=pop_loadset(fname);
data = pop_rejepoch(data, trials ,0);
data=pop_saveset(data,fname);

% Compute trial TF (not baseline-corrected)
std_ersp(data, 'type', 'ersp',...
    'trialindices', [1:data.trials], 'cycles', 0,...
    'nfreqs', 100, 'ntimesout', 400,...
    'freqs', [2 35], 'freqscale', 'linear',...
    'baseline', NaN, 'winsize',128,...
    'padratio', 16, 'channels', {data.chanlocs.labels}',...
    'verbose', 'on', 'savefile', 'on', 'recompute', 'on',...
    'savetrials', 'on'); 